platform :ios, '15.0'

use_frameworks!
target 'JXPagingViewExample' do
pod 'JXPagingView/Paging', :path => '../../../JXPagingView'
pod 'MJRefresh', '3.4.0'
pod 'JXSegmentedView', :path => '../../Sources/JXSegmentedView'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = '6'
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end
